apps/api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("system_status/", views.SystemStatusView.as_view(), name="system_status"),
    path("user/settings/", views.UserSettingsView.as_view(), name="user_settings"),
    path("subscribe/", views.SubscribeView.as_view(), name="subscribe"),
    path("reset_ss_port/", views.ReSetSSPortView.as_view(), name="reset_ss_port"),
    path("gen/invitecode/", views.gen_invite_code, name="geninvitecode"),
    path("shop/", views.purchase, name="purchase"),
    path("change/theme/", views.change_theme, name="change_theme"),
    path("change/sub_type/", views.change_sub_type, name="change_sub_type"),
    path("checkin/", views.UserCheckInView.as_view(), name="checkin"),
    # web api 接口
    path(
        "user_ss_config/<int:node_id>/",
        views.UserSSConfigView.as_view(),
        name="user_ss_config",
    ),
    path(
        "user_vmess_config/<int:node_id>/",
        views.UserVmessConfigView.as_view(),
        name="user_vmess_config",
    ),
    path(
        "vmess_server_config/<int:node_id>/",
        views.VmessServerConfigView.as_view(),
        name="vmess_server_config",
    ),
    path(
        "relay_server_config/<int:node_id>/",
        views.RelayServerConfigView.as_view(),
        name="relay_server_config",
    ),
    # 支付
    path("orders", views.OrderView.as_view(), name="order"),
    path("callback/alipay", views.ailpay_callback, name="alipay_callback"),
    # user stats
    path(
        "user/stats/ref_chart", views.UserRefChartView.as_view(), name="user_ref_chart"
    ),
    path(
        "user/stats/traffic_chart",
        views.UserTrafficChartView.as_view(),
        name="user_traffic_chart",
    ),
]

apps/sspanel/urls.py
from django.urls import path
from apps.sspanel import views, admin_views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path("", views.IndexView.as_view(), name="index"),
    path("help/", views.HelpView.as_view(), name="help"),
    path("client/", views.ClientView.as_view(), name="client"),
    # 邀请
    path("invitecode/", views.InviteCodeView.as_view(), name="invite_code"),
    # 注册/登录
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.UserLogInView.as_view(), name="login"),
    path("logout/", views.UserLogOutView.as_view(), name="logout"),
    # 节点
    path("nodeinfo/", views.NodeInfoView.as_view(), name="nodeinfo"),
    path("user_traffic_log/", views.UserTrafficLog.as_view(), name="user_traffic_log"),
    # 用户信息
    path("users/userinfo/", views.UserInfoView.as_view(), name="userinfo"),
    # 捐赠/充值
    path("donate/", views.DonateView.as_view(), name="donate"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("purchaselog/", views.PurchaseLogView.as_view(), name="purchaselog"),
    path("chargecenter/", views.ChargeView.as_view(), name="chargecenter"),
    # 公告
    path("announcement/", views.AnnouncementView.as_view(), name="announcement"),
    # 工单
    path("tickets/", views.TicketsView.as_view(), name="tickets"),
    path("tickets/(<int:pk>)/", views.TicketDetailView.as_view(), name="ticket_detail"),
    path("ticket_create/", views.TicketCreateView.as_view(), name="ticket_create"),
    path(
        "ticket_delete/<int:pk>)/",
        views.TicketDeleteView.as_view(),
        name="ticket_delete",
    ),
    # 推广相关
    path("aff/invite/", views.AffInviteView.as_view(), name="aff_invite"),
    path("aff/status/", views.AffStatusView.as_view(), name="aff_status"),
    # ====================================================================
    # 网站后台界面
    # ====================================================================
    path(
        "my_admin/user_online_ip_log/",
        admin_views.UserOnlineIpLogView.as_view(),
        name="user_online_ip_log",
    ),
    path("my_admin/", admin_views.SystemStatusView.as_view(), name="system_status"),
    # 邀请码相关
    path("my_admin/invite/", admin_views.InviteCodeView.as_view(), name="admin_invite"),
    # 节点相关
    path(
        "my_admin/node_list/",
        admin_views.NodeListView.as_view(),
        name="admin_node_list",
    ),
    path(
        "my_admin/node/<str:node_type>/",
        admin_views.NodeView.as_view(),
        name="admin_node",
    ),
    path(
        "my_admin/node_delete/<str:node_type>/<int:node_id>/",
        admin_views.NodeDeleteView.as_view(),
        name="admin_node_delete",
    ),
    path(
        "my_admin/ss_node/<str:node_type>/<int:node_id>/",
        admin_views.NodeDetailView.as_view(),
        name="admin_node_detail",
    ),
    # 用户相关
    path(
        "my_admin/user_list/",
        admin_views.UserListView.as_view(),
        name="admin_user_list",
    ),
    path(
        "my_admin/user/delete/<int:pk>/",
        admin_views.UserDeleteView.as_view(),
        name="admin_user_delete",
    ),
    path(
        "my_admin/user/search/",
        admin_views.UserSearchView.as_view(),
        name="admin_user_search",
    ),
    path(
        "my_admin/user/<int:pk>/",
        admin_views.UserDetailView.as_view(),
        name="admin_user_detail",
    ),
    path(
        "my_admin/user_status/",
        admin_views.UserStatusView.as_view(),
        name="admin_user_status",
    ),
    # 商品充值相关
    path("my_admin/charge/", admin_views.ChargeView.as_view(), name="admin_charge"),
    path("my_admin/goods/", admin_views.GoodsView.as_view(), name="admin_goods"),
    path(
        "my_admin/goods/<int:pk>/",
        admin_views.GoodDetailView.as_view(),
        name="good_detail",
    ),
    path(
        "my_admin/good_delete/<int:pk>/",
        admin_views.GoodDeleteView.as_view(),
        name="good_delete",
    ),
    path(
        "my_admin/good_create/",
        admin_views.GoodsCreateView.as_view(),
        name="good_create",
    ),
    path(
        "my_admin/purchase/history/",
        admin_views.PurchaseHistoryView.as_view(),
        name="purchase_history",
    ),
    # 公告管理相关
    path(
        "my_admin/announcements/",
        admin_views.AnnouncementsView.as_view(),
        name="admin_announcements",
    ),
    path(
        "my_admin/announcements/<int:pk>/",
        admin_views.AnnouncementDetailView.as_view(),
        name="announcement_detail",
    ),
    path(
        "my_admin/announcement_delete/<int:pk>/",
        admin_views.AnnouncementDeleteView.as_view(),
        name="announcement_delete",
    ),
    path(
        "my_admin/announcement_create/",
        admin_views.AnnouncementCreateView.as_view(),
        name="announcement_create",
    ),
    # 工单相关
    path("my_admin/tickets/", admin_views.TicketsView.as_view(), name="admin_tickets"),
    path(
        "my_admin/tickets/<int:pk>/",
        admin_views.TicketDetailView.as_view(),
        name="admin_ticket_detail",
    ),
]

apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path("", index, name="index"),
    path("", include("apps.sspanel.urls", namespace="sspanel")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls, name="admin"),
    # deprecated
    path("prom/", include("django_prometheus.urls")),
]

templates/my_admin/announcement_create.html
{% extends 'adminbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    创建新的公告：
                </h1>
                <h2 class="subtitle">
                    公告格式采用
                    <strong>Markdown</strong>
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %}
            <div class="control is-loading">
                <textarea class="textarea" id="id-markdown-body" name="body" type="text" rows="10"></textarea>
            </div>
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:admin_announcements' %}">取消</a>
            </div>
        </form>
    </div>
</div>
<script>
    var simplemde = new SimpleMDE({ spellChecker: false, element: $("#id-markdown-body")[0] });
</script> {% endblock main %}

templates/my_admin/announcement_detail.html
 {% extends 'adminbase.html' %} {% block main %} {% load ehcofilter %}

<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    公告编辑：
                </h1>
                <h2 class="subtitle">
                    格式采用Markdown！
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %}
            <div class="control is-loading">
                <textarea class="textarea" id="id-markdown-body" name="body" type="text" rows="10">{{ anno.body }}</textarea>
            </div>
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认修改</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:admin_announcements' %}">取消修改</a>
            </div>
        </form>
    </div>
</div>
<script>
    var simplemde = new SimpleMDE({ spellChecker: false,element: $("#id-markdown-body")[0] });
</script> {% endblock main %}

templates/my_admin/announcements.html
{% extends 'adminbase.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    公告列表：
                </h1>
                <h2 class="subtitle">
                    领导请下放通知!
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>日期</th>
                    <th>内容:</th>
                </tr>
            </thead>
            {% for rec in anno %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'sspanel:announcement_detail' rec.pk %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ rec.pk }}">删除</a>
                    </p>
                </td>
                <td>#{{ rec.pk}}</td>
                <td>{{ rec.time }}</td>
                <td>{{ rec.body |safe }}</td>
            </tr>
            <div class="modal user_delete" id="modal-{{ rec.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">ID:{{ rec.pk }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:
                            <code>{{ rec.pk }}</code>号公告么?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'sspanel:announcement_delete' rec.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <p class="subtitle">没有公告哟</p>
            {% endfor %}
        </table>
        <p align="right">
            <a class="button is-danger is-outlined" href="{% url 'sspanel:announcement_create' %}">增加公告</a>
        </p>
    </div>
</div>

{% endblock main %}

templates/my_admin/good_create.html
 {% extends 'adminbase.html' %} {% block main %} {% load ehcofilter %}

<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    创建新的商品：
                </h1>
                <h2 class="subtitle">
                    请在下方填写符合规则的商品信息
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %} {{ form.non_field_errors }} {% for field in form %} {{ field.label_tag }} {{ field|add_class:"input" }}
            {{ field.errors }} {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %} {% endfor %}
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:admin_goods' %}">取消</a>
            </div>
        </form>
    </div>
</div>

{% endblock main %}

templates/my_admin/index.html
{% extends 'adminbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    汇总：
                </h1>
                <h2 class="subtitle">
                    下面是系统运行状态简报：
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="tile is-ancestor">
        <div class="tile is-6 is-vertical is-parent">
            <div class="tile is-child box">
                <canvas id="userState" width="auto" height="300"></canvas>
            </div>
        </div>
        <div class="tile is-6 is-vertical is-parent">
            <div class="tile is-child box">
                <canvas id="nodeState"></canvas>
            </div>
            <div class="tile is-child box">
                <canvas id="donateState"></canvas>
            </div>
        </div>
    </div>
</div>
<script>
    // 获取后台首页状态
    var getSystemStatus = function () {
        $.getJSON("{% url 'api:system_status' %}", function (res) {
            genDoughnutChart('userState', '总用户:{{ total_user_num }} ',
                ['在线人数', '今日注册', '今日签到', '从未使用'],
                res.user_status)
            genDoughnutChart('nodeState', '节点流量 单位：GB',
                res.node_status.names, res.node_status.traffics)
            genDoughnutChart('donateState', '收入分析',
                ['总成交数', '总收入', '今日成交数', '今日收入'], res.donate_status)
        })
    }
    getSystemStatus()
</script> {% endblock main %}

templates/my_admin/node_detail.html
{% extends 'adminbase.html' %} {% block main %} {% load ehcofilter %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    配置编辑：
                </h1>
                <h2 class="subtitle">
                    编辑节点：{{ node.name }}
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %} {{ form.non_field_errors }}
            {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            <br>
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %}
            {% endfor %}
            <hr />
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认修改</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:admin_node_list' %}">取消修改</a>
            </div>
        </form>
    </div>
</div>

{% endblock main %}

templates/my_admin/node_list.html
{% extends 'adminbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    节点列表：
                </h1>
                <h2 class="subtitle">
                    添加或者删除节点：
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box table-container">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作</th>
                    <th>ID/类型</th>
                    <th>名字</th>
                    <th>地址</th>
                    <th>等级</th>
                    <th>上线</th>
                    <th>人/连接</th>
                    <th>已用/总流量</th>
                    <th>限速</th>
                    <th>对接</th>
                </tr>
            </thead>
            {% for node in node_list %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info modal-button"
                            href="{% url 'sspanel:admin_node_detail' node_type=node.node_type node_id=node.node_id  %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button"
                            data-target="modal-delete-{{ node.node_type }}-{{ node.node_id }}">删除</a>
                    </p>
                </td>
                <td>{{ node.node_id }}/{{ node.node_type }}</td>
                <td>{{ node.name }}</td>
                <td>{{ node.server }}</td>
                <td>{{ node.level }}</td>
                <td>{{ node.enable }}</td>
                <td>{{ node.online_user_count }}/{{ node.active_tcp_connections }}</td>
                <td>{{ node.human_used_traffic}}/{{ node.human_total_traffic }}</td>
                <td>{{ node.human_speed_limit }}</td>
                <td>
                    <p class="control">
                        <span class="icon  button modal-button is-medium"
                            data-target="modal-node-{{ node.node_type }}-{{ node.node_id }}">
                            <i class="fa fa-rocket"></i>
                        </span>
                    </p>
                </td>
            </tr>
            <div class="modal" id="modal-node-{{ node.node_type }}-{{ node.node_id }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">{{ node.name }} - 对接配置</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        {% if node.node_type == "ss" %}
                        <p class="subtitle"><a class="is-link" href="https://github.com/Ehco1996/aioshadowsocks">专用SS后端
                            </a>对接地址:</p>
                        {% else %}
                        <p class="subtitle"><a class="is-link" href="https://github.com/Ehco1996/v2scar">专用V2ray
                            </a>后端对接地址:</p>
                        {% endif %}
                        <div class="field is-grouped">
                            <p class="control is-expanded">
                                <input class="input" id="id-api-endpoint-{{ node.node_type }}-{{ node.node_id }}"
                                    value="{{ node.api_endpoint }}" readonly>
                            </p>
                            <a class="button is-rounded" id="id-button-clip"
                                data-clipboard-target="#id-api-endpoint-{{ node.node_type }}-{{ node.node_id }}">
                                <i class="fa fa-clipboard" aria-hidden="true"></i>
                            </a>
                        </div>
                        {% if node.node_type == "vmess" %}
                        <hr>
                        <p class="subtitle">Vmess 配置地址:</p>
                        <div class="field is-grouped">
                            <p class="control is-expanded">
                                <input class="input" id="id-vmess-config-{{ node.node_type }}-{{ node.node_id }}"
                                    value="{{ node.server_config_endpoint }}" readonly>
                            </p>
                            <a class="button is-rounded" id="id-button-clip"
                                data-clipboard-target="#id-vmess-config-{{ node.node_type }}-{{ node.node_id }}">
                                <i class="fa fa-clipboard" aria-hidden="true"></i>
                            </a>
                        </div>
                        {% if node.enable_relay %}
                        <hr>
                        <p class="subtitle">Relay 配置地址:</p>
                        <div class="field is-grouped">
                            <p class="control is-expanded">
                                <input class="input" id="id-relay-config-{{ node.node_type }}-{{ node.node_id }}" value="{{ node.relay_config_endpoint }}" readonly>
                            </p>
                            <a class="button is-rounded" id="id-button-clip" data-clipboard-target="#id-relay-config-{{ node.node_type }}-{{ node.node_id }}">
                                <i class="fa fa-clipboard" aria-hidden="true"></i>
                            </a>
                        </div>
                        {% endif %}
                        {% endif %}
                        <span class="copied" hidden="true">Copied!</span>
                    </section>
                </div>
            </div>
            <div class="modal node_delete" id="modal-delete-{{ node.node_type }}-{{ node.node_id }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">节点名:{{ node.name }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:
                            <code>{{ node.name }}</code>?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined"
                                href="{% url 'sspanel:admin_node_delete' node_type=node.node_type node_id=node.node_id %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <h2 class=" subtitle">
                暂时没有节点，点击下方按钮添加节点
            </h2>
            {% endfor %}
        </table>
        <p align="right">
            <a class="button is-danger is-outlined" href="{% url 'sspanel:admin_node' node_type='ss' %}">增加SS节点</a>
            <a class="button is-info is-outlined" href="{% url 'sspanel:admin_node' node_type='vmess' %}">增加VMESS节点</a>
        </p>
    </div>
</div>

<script>
    // 点击复制
    var clip = new Clipboard('#id-button-clip');
    clip.on('success', function (e) {
        $('.copied').show();
        $('.copied').fadeOut(1000);
    });
</script>
{% endblock main %}

templates/my_admin/ticket_detail.html
{% extends 'adminbase.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    查看工单：
                </h1>
                <h2 class="subtitle">
                    看看怎么处理吧！
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %}
            <div class="control is-loading">
                <span class="tag is-info">标题:</span>
                <textarea class="textarea" name="title" type="text" placeholder="标题" rows="1" maxlength="32">{{ ticket.title }}</textarea>
                <br>
                <span class="tag is-info">内容:</span>
                <textarea class="textarea" id="id-markdown-body" name="body" type="text" rows="10">{{ ticket.body }}</textarea>
                <span class="tag is-info">状态:</span>
                <div class="control">
                    <label class="radio">
                        <input type="radio" name="status" value="1"> 开启
                    </label>
                    <label class="radio">
                        <input type="radio" name="status" value="-1"> 关闭
                    </label>
                </div>
            </div>
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:admin_tickets' %}">取消</a>
            </div>
        </form>
    </div>
</div>
<script>
    var simplemde = new SimpleMDE({ spellChecker: false, element: $("#id-markdown-body")[0] });
    simplemde.togglePreview();
</script> {% endblock main %}

templates/my_admin/user_detail.html
 {% extends 'adminbase.html' %} {% block main %} {% load ehcofilter %}

<div class="column is-12">
    <section class="hero is-light is-small">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户编辑：
                </h1>
                <h2 class="subtitle">
                    编辑信息：{{ user }}
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="box">
        <form class="form" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field.label_tag }}
                    {{ field}}
                    {{ field.errors}}
                    {% if field.help_text %}
                    <p class="help is-danger">{{ field.help_text|safe }}</p>
                    {% endif %}
            {% endfor %}
            <br>
            {{ userform.non_field_errors }}
            {% for field in userform %} {{ field.label_tag }} {{ field}} {{ field.errors}}
                {% if field.help_text %}
                <p class="help is-danger">{{ field.help_text|safe }}</p>
                {% endif %}
            {% endfor %}
            <br>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认修改</button>
                <a class="button is-success is-outlined" href="{% url 'sspanel:admin_user_list' %}">取消修改</a>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

templates/my_admin/user_list.html
{% extends 'adminbase.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户列表：
                </h1>
                <h2 class="subtitle">
                    给衣食父母们请安了!
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <form method="get" action="{% url 'sspanel:admin_user_search' %}">
        <div class="field has-addons">
            <div class="control">
                <input name="q" class="input" type="search" placeholder="用户名/邮箱 模糊搜索" required>
            </div>
            <div class="control">
                <button type="submit" class="button is-outlined is-info">搜索</button>
            </div>
        </div>
    </form>
    <br>
    <div class="box">
        <nav class="pagination">
            {% if contacts.has_previous %}
            <a class="pagination-previous" href="?page={{ contacts.previous_page_number }}">上一页</a> {% endif %}
            {% if contacts.has_next%}
            <a class="pagination-next" href="?page={{ contacts.next_page_number }}">下一页</a> {% endif %} {% if page %}
            <p>页码：</p>
            <ul class="pagination-list">
                {% if first %}
                <a href="?page=1" class="pagination-link">1</a>
                {% endif %} {% if left %} {% if left_has_more %}
                <span>...</span>
                {% endif %} {% for i in left %}
                <a href="?page={{ i }}" class="pagination-link">{{ i }}</a>
                {% endfor %} {% endif %}
                <a href="?page={{ page }}" class="pagination-link is-current">{{ page }}</a>
                {% if right %} {% for i in right%}
                <a href="?page={{ i }}" class="pagination-link">{{ i }}</a>
                {% endfor %} {% if right_has_more %}
                <span>...</span>
                {% endif %} {% endif %} {% if last %}
                <a href="?page={{ total }}" class="pagination-link">{{ total }}</a>
                {% endif %}
            </ul>
            {% endif %}
        </nav>
        <br>
        <div class="table-container">
            <table class="table is-fullwidth">
                <thead>
                    <tr>
                        <th>操作:</th>
                        <th>ID:</th>
                        <th>用户名</th>
                        <th>邮箱:</th>
                        <th>端口:</th>
                        <th>已用/总流量</th>
                    </tr>
                </thead>
                {% for contact in contacts %}
                <tr>
                    <td>
                        <p class="control">
                            <a class="button is-info" href="{% url 'sspanel:admin_user_detail' contact.pk %}">编辑</a>
                        </p>
                        <p class="control">
                            <a class="button is-danger modal-button" data-target="modal-{{ contact.pk }}">删除</a>
                        </p>
                    </td>
                    <td>#{{ contact.id}}</td>
                    <td>{{ contact.username }}</td>
                    <td>{{ contact.email }}</td>
                    <td>{{ contact.ss_port }}</td>
                    <td>{{ contact.human_used_traffic }} /
                        {{ contact.human_total_traffic }}
                    </td>
                </tr>
                <div class="modal user_delete" id="modal-{{ contact.pk }}">
                    <div class="modal-background"></div>
                    <div class="modal-card">
                        <header class="modal-card-head">
                            <p class="modal-card-title">用户名:{{ contact.username }}</p>
                            <button class="delete"></button>
                        </header>
                        <section class="modal-card-body">
                            <p class="subtitle">确定要删除:
                                <code>{{ contact.username }}</code>?</p>
                            <p align="center">
                                <a class="button is-danger is-outlined"
                                    href="{% url 'sspanel:admin_user_delete' contact.pk %}">确定删除</a>
                            </p>
                        </section>
                    </div>
                </div>
                {% empty %}
                <p class="subtitle">没有用户哟</p>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock main %}