apps/api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("system_status/", views.SystemStatusView.as_view(), name="system_status"),
    path("user/settings/", views.UserSettingsView.as_view(), name="user_settings"),
    path("subscribe/", views.SubscribeView.as_view(), name="subscribe"),
    path("reset_ss_port/", views.ReSetSSPortView.as_view(), name="reset_ss_port"),
    path("gen/invitecode/", views.gen_invite_code, name="geninvitecode"),
    path("shop/", views.purchase, name="purchase"),
    path("change/theme/", views.change_theme, name="change_theme"),
    path("change/sub_type/", views.change_sub_type, name="change_sub_type"),
    path("checkin/", views.UserCheckInView.as_view(), name="checkin"),
    # web api 接口
    path(
        "user_ss_config/<int:node_id>/",
        views.UserSSConfigView.as_view(),
        name="user_ss_config",
    ),
    path(
        "user_vmess_config/<int:node_id>/",
        views.UserVmessConfigView.as_view(),
        name="user_vmess_config",
    ),
    path(
        "vmess_server_config/<int:node_id>/",
        views.VmessServerConfigView.as_view(),
        name="vmess_server_config",
    ),
    path(
        "relay_server_config/<int:node_id>/",
        views.RelayServerConfigView.as_view(),
        name="relay_server_config",
    ),
    # 支付
    path("orders", views.OrderView.as_view(), name="order"),
    path("callback/alipay", views.ailpay_callback, name="alipay_callback"),
    # user stats
    path(
        "user/stats/ref_chart", views.UserRefChartView.as_view(), name="user_ref_chart"
    ),
    path(
        "user/stats/traffic_chart",
        views.UserTrafficChartView.as_view(),
        name="user_traffic_chart",
    ),
]

apps/sspanel/urls.py
from django.urls import path
from apps.sspanel import views, admin_views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path("", views.IndexView.as_view(), name="index"),
    path("help/", views.HelpView.as_view(), name="help"),
    path("client/", views.ClientView.as_view(), name="client"),
    # 邀请
    path("invitecode/", views.InviteCodeView.as_view(), name="invite_code"),
    # 注册/登录
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.UserLogInView.as_view(), name="login"),
    path("logout/", views.UserLogOutView.as_view(), name="logout"),
    # 节点
    path("nodeinfo/", views.NodeInfoView.as_view(), name="nodeinfo"),
    path("user_traffic_log/", views.UserTrafficLog.as_view(), name="user_traffic_log"),
    # 用户信息
    path("users/userinfo/", views.UserInfoView.as_view(), name="userinfo"),
    # 捐赠/充值
    path("donate/", views.DonateView.as_view(), name="donate"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("purchaselog/", views.PurchaseLogView.as_view(), name="purchaselog"),
    path("chargecenter/", views.ChargeView.as_view(), name="chargecenter"),
    # 公告
    path("announcement/", views.AnnouncementView.as_view(), name="announcement"),
    # 工单
    path("tickets/", views.TicketsView.as_view(), name="tickets"),
    path("tickets/(<int:pk>)/", views.TicketDetailView.as_view(), name="ticket_detail"),
    path("ticket_create/", views.TicketCreateView.as_view(), name="ticket_create"),
    path(
        "ticket_delete/<int:pk>)/",
        views.TicketDeleteView.as_view(),
        name="ticket_delete",
    ),
    # 推广相关
    path("aff/invite/", views.AffInviteView.as_view(), name="aff_invite"),
    path("aff/status/", views.AffStatusView.as_view(), name="aff_status"),
    # ====================================================================
    # 网站后台界面
    # ====================================================================
    path(
        "my_admin/user_online_ip_log/",
        admin_views.UserOnlineIpLogView.as_view(),
        name="user_online_ip_log",
    ),
    path("my_admin/", admin_views.SystemStatusView.as_view(), name="system_status"),
    # 邀请码相关
    path("my_admin/invite/", admin_views.InviteCodeView.as_view(), name="admin_invite"),
    # 节点相关
    path(
        "my_admin/node_list/",
        admin_views.NodeListView.as_view(),
        name="admin_node_list",
    ),
    path(
        "my_admin/node/<str:node_type>/",
        admin_views.NodeView.as_view(),
        name="admin_node",
    ),
    path(
        "my_admin/node_delete/<str:node_type>/<int:node_id>/",
        admin_views.NodeDeleteView.as_view(),
        name="admin_node_delete",
    ),
    path(
        "my_admin/ss_node/<str:node_type>/<int:node_id>/",
        admin_views.NodeDetailView.as_view(),
        name="admin_node_detail",
    ),
    # 用户相关
    path(
        "my_admin/user_list/",
        admin_views.UserListView.as_view(),
        name="admin_user_list",
    ),
    path(
        "my_admin/user/delete/<int:pk>/",
        admin_views.UserDeleteView.as_view(),
        name="admin_user_delete",
    ),
    path(
        "my_admin/user/search/",
        admin_views.UserSearchView.as_view(),
        name="admin_user_search",
    ),
    path(
        "my_admin/user/<int:pk>/",
        admin_views.UserDetailView.as_view(),
        name="admin_user_detail",
    ),
    path(
        "my_admin/user_status/",
        admin_views.UserStatusView.as_view(),
        name="admin_user_status",
    ),
    # 商品充值相关
    path("my_admin/charge/", admin_views.ChargeView.as_view(), name="admin_charge"),
    path("my_admin/goods/", admin_views.GoodsView.as_view(), name="admin_goods"),
    path(
        "my_admin/goods/<int:pk>/",
        admin_views.GoodDetailView.as_view(),
        name="good_detail",
    ),
    path(
        "my_admin/good_delete/<int:pk>/",
        admin_views.GoodDeleteView.as_view(),
        name="good_delete",
    ),
    path(
        "my_admin/good_create/",
        admin_views.GoodsCreateView.as_view(),
        name="good_create",
    ),
    path(
        "my_admin/purchase/history/",
        admin_views.PurchaseHistoryView.as_view(),
        name="purchase_history",
    ),
    # 公告管理相关
    path(
        "my_admin/announcements/",
        admin_views.AnnouncementsView.as_view(),
        name="admin_announcements",
    ),
    path(
        "my_admin/announcements/<int:pk>/",
        admin_views.AnnouncementDetailView.as_view(),
        name="announcement_detail",
    ),
    path(
        "my_admin/announcement_delete/<int:pk>/",
        admin_views.AnnouncementDeleteView.as_view(),
        name="announcement_delete",
    ),
    path(
        "my_admin/announcement_create/",
        admin_views.AnnouncementCreateView.as_view(),
        name="announcement_create",
    ),
    # 工单相关
    path("my_admin/tickets/", admin_views.TicketsView.as_view(), name="admin_tickets"),
    path(
        "my_admin/tickets/<int:pk>/",
        admin_views.TicketDetailView.as_view(),
        name="admin_ticket_detail",
    ),
]

apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path("", index, name="index"),
    path("", include("apps.sspanel.urls", namespace="sspanel")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls, name="admin"),
    # deprecated
    path("prom/", include("django_prometheus.urls")),
]

templates/adminbase.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load static %}
    <title>{% settings_value "TITLE" %}</title>
    {% include "basehead.html" %}
</head>

<body>
    <nav class="navbar is-primary is-spaced">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'sspanel:index' %}">首页</a>
                <a class="navbar-item" href="{% url 'sspanel:help' %}">使用说明</a>
                <a class="navbar-item" href="{% url 'sspanel:invite_code' %}">邀请码</a>
                <a class="navbar-item" href="{% url 'sspanel:client' %}">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-primary is-inverted" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'sspanel:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active">面板管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:system_status' %}">系统状态</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_invite' %}">邀请相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_announcements' %}">公告管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_tickets' %}">工单管理</a>
                    <a class="navbar-item is-active">节点管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_node_list' %}">节点列表</a>
                    <a class="navbar-item" href="{% url 'sspanel:user_online_ip_log' %}">在线IP</a>
                    <a class="navbar-item is-active">交易管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_charge' %}">充值管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_goods' %}">商品管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:purchase_history' %}">购买记录</a>
                    <a class="navbar-item is-active">用户管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_user_list' %}">用户列表</a>
                    <a class="navbar-item" href="{% url 'sspanel:admin_user_status' %}">用户分析</a>
                    <a class="navbar-item is-active">面板跳转</a>
                    <a class="navbar-item" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">用户面板</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="hero is-small is-primary">
        <!-- Hero content: will be in the middle -->
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    {% settings_value "SUBTITLE" %}
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <br />
    <div class="container">
        <div class="columns">
            <div class="column is-2 is-hidden-mobile">
                <div class="box">
                    {% if user.is_authenticated %}
                    <aside class="menu">
                        <p class="menu-label">
                            面板管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:system_status' %}">系统状态</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:admin_invite' %}">邀请相关</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:admin_announcements' %}">公告管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:admin_tickets' %}">工单管理</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            节点管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:admin_node_list' %}">节点列表</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:user_online_ip_log' %}">在线IP</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            交易管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:admin_charge' %}">充值管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:admin_goods' %}">商品管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:purchase_history' %}">购买记录</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            用户管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:admin_user_list' %}">用户列表</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:admin_user_status' %}">用户分析</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            面板跳转
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="/admin">数据后台</a>
                            </li>
                        </ul>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:userinfo' %}">用户面板</a>
                            </li>
                        </ul>
                        {% endif %}
                    </aside>
                </div>
            </div>
            <div class="column is-10">
                {% block main %} {% endblock main%}
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2020
                        <a href="https://github.com/Ehco1996">GitHub</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 -->
{% if messages %}
<script>
    {% for message in messages %}
    swal("{{ message.extra_tags }}", '{{ message }}', '{{ message.level_tag }}');
    {% endfor %}
</script>
{% endif %}

</html>

templates/base.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <title>{% settings_value "TITLE" %}</title>
    {% include "basehead.html" %}
</head>

<body>
    <nav class="navbar is-info">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="{% static 'img/logo/logo1.png' %}" alt="xyzlogo" width="112" height="28">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'sspanel:index' %}">Home</a>
                <a class="navbar-item" href="{% url 'sspanel:help' %}">How to install</a>
                <a class="navbar-item" href="{% url 'sspanel:invite_code' %}">Invitations</a>
                {% if user.is_authenticated %}
                <!-- <a class="navbar-item" href="{% url 'sspanel:client' %}">Download</a> -->
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-info is-inverted" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>Personal account</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'sspanel:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>Logout</span>
                        </a>
                    </div>
                </div>
                <hr>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <!-- <a class="navbar-item is-active">Information:</a> -->
                    <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">Personal account</a>
                    <a class="navbar-item" href="{% url 'sspanel:announcement' %}">News</a>
                    <!-- <a class="navbar-item" href="{% url 'sspanel:tickets' %}">Tickets</a> -->
                    <a class="navbar-item is-active">Nodes:</a>
                    <a class="navbar-item" href="{% url 'sspanel:nodeinfo' %}">All Servers</a>
                    <!-- <a class="navbar-item" href="{% url 'sspanel:user_traffic_log' %}">Traffic info</a> -->
                    <a class="navbar-item is-active">Payment:</a>
                    <!-- <a class="navbar-item" href="{% url 'sspanel:donate' %}">Donate</a>
                    <a class="navbar-item" href="{% url 'sspanel:chargecenter' %}">Top up</a> -->
                    <a class="navbar-item" href="{% url 'sspanel:shop' %}">Buy</a>
                    <a class="navbar-item" href="{% url 'sspanel:purchaselog' %}">Purchase history</a>
                    <a class="navbar-item is-active">Invitations:</a>
                    <a class="navbar-item" href="{% url 'sspanel:aff_invite' %}">To invite a friend</a>
                    <a class="navbar-item" href="{% url 'sspanel:aff_status' %}">Offers from invitations</a>
                    {% if perms.sspanel %}
                    <a class="navbar-item is-active">Control Panel</a>
                    <a class="navbar-item" href="/admin">Panel Django</a>
                    <a class="navbar-item" href="{% url 'sspanel:system_status' %}">CMS</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="columns">
            <div class="column is-2 is-hidden-mobile" style="margin-top: 12px;">
                <div class="box">
                    {% if user.is_authenticated %}
                    <aside class="menu">
                        <!-- <p class="menu-label">
                            Information:
                        </p> -->
                        <ul class="menu-list">
                            <li>
                                <a class="" href="{% url 'sspanel:userinfo' %}">Personal account</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:announcement' %}">News</a>
                            </li>
                            <!-- <li>
                                <a href="{% url 'sspanel:tickets' %}">Tickets</a>
                            </li> -->
                        </ul>
                        <p class="menu-label">
                            All Servers:
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:nodeinfo' %}">All Servers</a>
                            </li>
                            <!-- <li>
                                <a href="{% url 'sspanel:user_traffic_log' %}">Traffic info</a>
                            </li> -->
                        </ul>
                        <p class="menu-label">
                            Payment:
                        </p>
                        <ul class="menu-list">
                            <!-- <li>
                                <a href="{% url 'sspanel:donate' %}">Donate</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:chargecenter' %}">Top up</a>
                            </li> -->
                            <li>
                                <a href="{% url 'sspanel:shop' %}">Buy</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:purchaselog' %}">Purchase history</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            Invitations:
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:aff_invite' %}">To invite a friend</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:aff_status' %}">Offers from invitations</a>
                            </li>
                        </ul>
                        {% if perms.sspanel %}
                        <p class="menu-label">
                            Control Panel
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="/admin">Panel Django</a>
                            </li>
                        </ul>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:system_status' %}">CMS</a>
                            </li>
                        </ul>
                        {% endif %} {% else %}
                        <article class="message is-light">
                            <div class="message-header">
                                <p>XYZ-1</p>
                            </div>
                            <div class="message-body">
                                25 元/30 days/500 GB
                            </div>
                        </article>
                        <article class="message is-light">
                            <div class="message-header">
                                <p>XYZ-3</p>
                            </div>
                            <div class="message-body">
                                70 元/90 days/1500 GB
                            </div>
                        </article>
                        <article class="message is-light">
                            <div class="message-header">
                                <p>XYZ-6</p>
                            </div>
                            <div class="message-body">
                                135 元/180 days/3000 GB
                            </div>
                        </article>
                        <article class="message is-light">
                            <div class="message-header">
                                <p>XYZ-12</p>
                            </div>
                            <div class="message-body">
                                270 元/360 days/6000 GB
                            </div>
                        </article>
                        {% endif %}
                    </aside>
                </div>
            </div>

            <div class="column is-10" >
                {% block main %} {% endblock main%}
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2018-2020·
                        <a href="https://yxorp.xyz">Yxorp</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 TODO 这里写成函数-->
{% if messages %}
<script>
    {% for message in messages %}
    swal("{{ message.extra_tags }}", '{{ message }}', '{{ message.level_tag }}');
    {% endfor %}
</script>
{% endif %}

</html>

templates/basehead.html
{% load static %}
<!-- meta -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="{% static 'img/logo/logo.ico' %}" type="image/x-icon" />
<!-- css -->
{% if user.theme and user.theme != "default" %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bulmaswatch/0.7.5/{{ user.theme }}/bulmaswatch.min.css"
    rel="stylesheet">
{% else %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.min.css" rel="stylesheet">
{% endif %}
<link rel="stylesheet" href="{% static 'sspanel/css/sspanel.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplemde/1.11.2/simplemde.min.css"
    rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css"
    rel="stylesheet">

<!-- js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/simplemde/1.11.2/simplemde.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js"></script>
<script src="{% static 'sspanel/js/sspanel.js' %}"></script>