apps/api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("system_status/", views.SystemStatusView.as_view(), name="system_status"),
    path("user/settings/", views.UserSettingsView.as_view(), name="user_settings"),
    path("subscribe/", views.SubscribeView.as_view(), name="subscribe"),
    path("reset_ss_port/", views.ReSetSSPortView.as_view(), name="reset_ss_port"),
    path("gen/invitecode/", views.gen_invite_code, name="geninvitecode"),
    path("shop/", views.purchase, name="purchase"),
    path("change/theme/", views.change_theme, name="change_theme"),
    path("change/sub_type/", views.change_sub_type, name="change_sub_type"),
    path("checkin/", views.UserCheckInView.as_view(), name="checkin"),
    # web api 接口
    path(
        "user_ss_config/<int:node_id>/",
        views.UserSSConfigView.as_view(),
        name="user_ss_config",
    ),
    path(
        "user_vmess_config/<int:node_id>/",
        views.UserVmessConfigView.as_view(),
        name="user_vmess_config",
    ),
    path(
        "vmess_server_config/<int:node_id>/",
        views.VmessServerConfigView.as_view(),
        name="vmess_server_config",
    ),
    path(
        "relay_server_config/<int:node_id>/",
        views.RelayServerConfigView.as_view(),
        name="relay_server_config",
    ),
    # 支付
    path("orders", views.OrderView.as_view(), name="order"),
    path("callback/alipay", views.ailpay_callback, name="alipay_callback"),
    # user stats
    path(
        "user/stats/ref_chart", views.UserRefChartView.as_view(), name="user_ref_chart"
    ),
    path(
        "user/stats/traffic_chart",
        views.UserTrafficChartView.as_view(),
        name="user_traffic_chart",
    ),
]

apps/sspanel/urls.py
from django.urls import path
from apps.sspanel import views, admin_views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path("", views.IndexView.as_view(), name="index"),
    path("help/", views.HelpView.as_view(), name="help"),
    path("client/", views.ClientView.as_view(), name="client"),
    # 邀请
    path("invitecode/", views.InviteCodeView.as_view(), name="invite_code"),
    # 注册/登录
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.UserLogInView.as_view(), name="login"),
    path("logout/", views.UserLogOutView.as_view(), name="logout"),
    # 节点
    path("nodeinfo/", views.NodeInfoView.as_view(), name="nodeinfo"),
    path("user_traffic_log/", views.UserTrafficLog.as_view(), name="user_traffic_log"),
    # 用户信息
    path("users/userinfo/", views.UserInfoView.as_view(), name="userinfo"),
    # 捐赠/充值
    path("donate/", views.DonateView.as_view(), name="donate"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("purchaselog/", views.PurchaseLogView.as_view(), name="purchaselog"),
    path("chargecenter/", views.ChargeView.as_view(), name="chargecenter"),
    # 公告
    path("announcement/", views.AnnouncementView.as_view(), name="announcement"),
    # 工单
    path("tickets/", views.TicketsView.as_view(), name="tickets"),
    path("tickets/(<int:pk>)/", views.TicketDetailView.as_view(), name="ticket_detail"),
    path("ticket_create/", views.TicketCreateView.as_view(), name="ticket_create"),
    path(
        "ticket_delete/<int:pk>)/",
        views.TicketDeleteView.as_view(),
        name="ticket_delete",
    ),
    # 推广相关
    path("aff/invite/", views.AffInviteView.as_view(), name="aff_invite"),
    path("aff/status/", views.AffStatusView.as_view(), name="aff_status"),
    # ====================================================================
    # 网站后台界面
    # ====================================================================
    path(
        "my_admin/user_online_ip_log/",
        admin_views.UserOnlineIpLogView.as_view(),
        name="user_online_ip_log",
    ),
    path("my_admin/", admin_views.SystemStatusView.as_view(), name="system_status"),
    # 邀请码相关
    path("my_admin/invite/", admin_views.InviteCodeView.as_view(), name="admin_invite"),
    # 节点相关
    path(
        "my_admin/node_list/",
        admin_views.NodeListView.as_view(),
        name="admin_node_list",
    ),
    path(
        "my_admin/node/<str:node_type>/",
        admin_views.NodeView.as_view(),
        name="admin_node",
    ),
    path(
        "my_admin/node_delete/<str:node_type>/<int:node_id>/",
        admin_views.NodeDeleteView.as_view(),
        name="admin_node_delete",
    ),
    path(
        "my_admin/ss_node/<str:node_type>/<int:node_id>/",
        admin_views.NodeDetailView.as_view(),
        name="admin_node_detail",
    ),
    # 用户相关
    path(
        "my_admin/user_list/",
        admin_views.UserListView.as_view(),
        name="admin_user_list",
    ),
    path(
        "my_admin/user/delete/<int:pk>/",
        admin_views.UserDeleteView.as_view(),
        name="admin_user_delete",
    ),
    path(
        "my_admin/user/search/",
        admin_views.UserSearchView.as_view(),
        name="admin_user_search",
    ),
    path(
        "my_admin/user/<int:pk>/",
        admin_views.UserDetailView.as_view(),
        name="admin_user_detail",
    ),
    path(
        "my_admin/user_status/",
        admin_views.UserStatusView.as_view(),
        name="admin_user_status",
    ),
    # 商品充值相关
    path("my_admin/charge/", admin_views.ChargeView.as_view(), name="admin_charge"),
    path("my_admin/goods/", admin_views.GoodsView.as_view(), name="admin_goods"),
    path(
        "my_admin/goods/<int:pk>/",
        admin_views.GoodDetailView.as_view(),
        name="good_detail",
    ),
    path(
        "my_admin/good_delete/<int:pk>/",
        admin_views.GoodDeleteView.as_view(),
        name="good_delete",
    ),
    path(
        "my_admin/good_create/",
        admin_views.GoodsCreateView.as_view(),
        name="good_create",
    ),
    path(
        "my_admin/purchase/history/",
        admin_views.PurchaseHistoryView.as_view(),
        name="purchase_history",
    ),
    # 公告管理相关
    path(
        "my_admin/announcements/",
        admin_views.AnnouncementsView.as_view(),
        name="admin_announcements",
    ),
    path(
        "my_admin/announcements/<int:pk>/",
        admin_views.AnnouncementDetailView.as_view(),
        name="announcement_detail",
    ),
    path(
        "my_admin/announcement_delete/<int:pk>/",
        admin_views.AnnouncementDeleteView.as_view(),
        name="announcement_delete",
    ),
    path(
        "my_admin/announcement_create/",
        admin_views.AnnouncementCreateView.as_view(),
        name="announcement_create",
    ),
    # 工单相关
    path("my_admin/tickets/", admin_views.TicketsView.as_view(), name="admin_tickets"),
    path(
        "my_admin/tickets/<int:pk>/",
        admin_views.TicketDetailView.as_view(),
        name="admin_ticket_detail",
    ),
]

apps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path("", index, name="index"),
    path("", include("apps.sspanel.urls", namespace="sspanel")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls, name="admin"),
    # deprecated
    path("prom/", include("django_prometheus.urls")),
]

apps/sspanel/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from apps.constants import METHOD_CHOICES, THEME_CHOICES
from apps.sspanel.forms import LoginForm, RegisterForm
from apps.sspanel.models import (
    Announcement,
    Donate,
    Goods,
    InviteCode,
    MoneyCode,
    PurchaseHistory,
    RebateRecord,
    Ticket,
    User,
    SSNode,
    VmessNode,
)
from apps.utils import traffic_format


class IndexView(View):
    def get(self, request):
        """跳转到首页"""
        return render(request, "sspanel/index.html")


class HelpView(View):
    def get(self, request):
        """跳转到帮助界面"""
        return render(request, "sspanel/help.html")


class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("sspanel:userinfo"))
        ref = request.GET.get("ref")
        if ref:
            form = RegisterForm(initial={"ref": ref})
        else:
            form = RegisterForm(initial={"invitecode": request.GET.get("invitecode")})
        return render(request, "sspanel/register.html", {"form": form})

    def post(self, request):
        if not settings.ALLOW_REGISTER:
            return HttpResponse("已经关闭注册了喵")

        form = RegisterForm(data=request.POST)
        if form.is_valid():
            user = User.add_new_user(form.cleaned_data)
            if not user:
                messages.error(request, "服务出现了点小问题", extra_tags="请尝试或者联系站长~")
                return render(request, "sspanel/register.html", {"form": form})
            else:
                messages.success(request, "自动跳转到用户中心", extra_tags="注册成功！")
                user = authenticate(
                    username=form.cleaned_data["username"],
                    password=form.cleaned_data["password1"],
                )
                login(request, user)
                return HttpResponseRedirect(reverse("sspanel:userinfo"))
        return render(request, "sspanel/register.html", {"form": form})


class UserLogInView(View):
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user and user.is_active:
                login(request, user)
                messages.success(request, "You will automatically be taken to the personal account", extra_tags="Success")
                return HttpResponseRedirect(reverse("sspanel:userinfo"))
            else:
                messages.error(request, "Please enter data correctly", extra_tags="ERROR")

        context = {"form": LoginForm()}
        return render(request, "sspanel/login.html", context=context)

    def get(self, request):
        context = {"form": LoginForm()}
        return render(request, "sspanel/login.html", context=context)


class UserLogOutView(View):
    def get(self, request):
        logout(request)
        messages.warning(request, "Thank you for spending time with us", extra_tags="Successful Exit")
        return HttpResponseRedirect(reverse("sspanel:index"))


class InviteCodeView(View):
    def get(self, request):
        code_list = InviteCode.list_by_code_type(InviteCode.TYPE_PUBLIC)
        return render(request, "sspanel/invite.html", context={"code_list": code_list})


class AffInviteView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        context = {
            "code_list": InviteCode.list_by_user_id(user.pk),
            "invite_percent": settings.INVITE_PERCENT * 100,
            "invitecode_num": InviteCode.calc_num_by_user(user),
            "ref_link": user.ref_link,
        }
        return render(request, "sspanel/aff_invite.html", context=context)


class AffStatusView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        rebate_logs = RebateRecord.list_by_user_id_with_consumer_username(user.pk)
        bar_config = {
            "labels": ["z", "v", "x", "x", "z", "v", "x", "x", "z", "v"],
            "data": [1, 2, 3, 4, 1, 1, 1, 1, 1, 2],
            "data_title": "Daily registration number",
        }
        context = {"rebate_logs": rebate_logs, "user": user, "bar_config": bar_config}
        return render(request, "sspanel/aff_status.html", context=context)


class UserInfoView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        # 获取公告
        anno = Announcement.objects.first()
        min_traffic = traffic_format(settings.MIN_CHECKIN_TRAFFIC)
        max_traffic = traffic_format(settings.MAX_CHECKIN_TRAFFIC)
        context = {
            "user": user,
            "anno": anno,
            "min_traffic": min_traffic,
            "max_traffic": max_traffic,
            "themes": THEME_CHOICES,
            "sub_link": user.sub_link,
            "sub_types": User.SUB_TYPES,
            "user_sub_type": user.get_sub_type_display(),
            "methods": [m[0] for m in METHOD_CHOICES],
        }
        return render(request, "sspanel/userinfo.html", context=context)


class NodeInfoView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        # ss node
        ss_node_list = [
            node.to_dict_with_extra_info(user) for node in SSNode.get_active_nodes()
        ]
        # vmess node
        vmess_node_list = [
            node.to_dict_with_extra_info(user) for node in VmessNode.get_active_nodes()
        ]
        context = {
            "ss_node_list": ss_node_list,
            "vmess_node_list": vmess_node_list,
            "user": user,
        }
        Announcement.send_first_visit_msg(request)
        return render(request, "sspanel/nodeinfo.html", context=context)


class UserTrafficLog(LoginRequiredMixin, View):
    def get(self, request):
        ss_node_list = SSNode.get_active_nodes()
        vmess_node_list = VmessNode.get_active_nodes()
        context = {
            "user": request.user,
            "ss_node_list": ss_node_list,
            "vmess_node_list": vmess_node_list,
        }
        return render(request, "sspanel/user_traffic_log.html", context=context)


class ShopView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        goods = Goods.objects.filter(status=1)
        context = {"user": user, "goods": goods}
        return render(request, "sspanel/shop.html", context=context)


class ClientView(LoginRequiredMixin, View):
    def get(self, request):
        """跳转到客户端界面"""
        return render(request, "sspanel/client.html")


class DonateView(LoginRequiredMixin, View):
    def get(self, request):
        """捐赠界面和支付宝当面付功能"""
        donatelist = Donate.objects.all()[:8]
        context = {"donatelist": donatelist}
        return render(request, "sspanel/donate.html", context=context)


class PurchaseLogView(LoginRequiredMixin, View):
    def get(self, request):
        """用户购买记录页面"""

        records = PurchaseHistory.objects.filter(user=request.user)[:10]
        context = {"records": records}
        return render(request, "sspanel/purchaselog.html", context=context)


class ChargeView(LoginRequiredMixin, View):
    def get(self, request):
        """充值界面的跳转"""
        user = request.user
        codelist = MoneyCode.objects.filter(user=user)
        context = {"user": user, "codelist": codelist}
        return render(request, "sspanel/chargecenter.html", context=context)

    def post(self, request):
        user = request.user
        input_code = request.POST.get("chargecode")
        # 在数据库里检索充值
        code = MoneyCode.objects.filter(code=input_code).first()
        # 判断充值码是否存在
        if not code:
            messages.error(request, "请重新获取充值码", extra_tags="充值码失效")
            return HttpResponseRedirect(reverse("sspanel:chargecenter"))
        else:
            # 判断充值码是否被使用
            if code.isused is True:
                # 当被使用的是时候
                messages.error(request, "请重新获取充值码", extra_tags="充值码失效")
                return HttpResponseRedirect(reverse("sspanel:chargecenter"))
            else:
                # 充值操作
                user.balance += code.number
                code.user = user.username
                code.isused = True
                user.save()
                code.save()
                # 将充值记录和捐赠绑定
                Donate.objects.create(user=user, money=code.number)
                messages.success(request, "请去商店购买商品！", extra_tags="充值成功！")
                return HttpResponseRedirect(reverse("sspanel:chargecenter"))


class AnnouncementView(LoginRequiredMixin, View):
    def get(self, request):
        """网站公告列表"""
        anno = Announcement.objects.all()
        return render(request, "sspanel/announcement.html", {"anno": anno})


class TicketsView(LoginRequiredMixin, View):
    def get(self, request):
        """工单系统"""
        ticket = Ticket.objects.filter(user=request.user)
        context = {"ticket": ticket}
        return render(request, "sspanel/ticket.html", context=context)


class TicketCreateView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "sspanel/ticketcreate.html")

    def post(self, request):
        """工单提交"""
        title = request.POST.get("title", "")
        body = request.POST.get("body", "")
        Ticket.objects.create(user=request.user, title=title, body=body)
        messages.success(request, "数据更新成功！", extra_tags="添加成功")
        return HttpResponseRedirect(reverse("sspanel:tickets"))


class TicketDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        """工单编辑"""
        ticket = Ticket.objects.get(pk=pk)

templates/sspanel/help.html
{% extends 'base.html' %} {% block main %} {% load static %}
<div class="column is-12">
    <section class="hero is-info is-small">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    How to install
                </h1>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">
        <h2 class="subtitle">
            Download:
        </h2>
        <p><a class="download_link" href="/static/media/clients/clash.apk">Clash for Android</a>  <br>       
            <a class="download_link" href="/static/media/clients/clashX.dmg">Clash for Mac OS</a>     <br>
            <a class="download_link" href="/static/media/clients/clash.exe">Clash for Windows</a> <br>
            <a href="https://apps.apple.com/us/app/quantumult/id1252015438">Quantumult for IOS</a><br>
            <a href="https://apps.apple.com/us/app/pepi/id1283082051">Pepi for IOS</a><br>
            <a href="https://apps.apple.com/us/app/shadowrocket/id932747118">Shadowrocket for IOS </a><br>
            <a href="https://apps.apple.com/us/app/i2ray/id1445270056">i2Ray for IOS</a><br>
            <a href="https://apps.apple.com/us/app/kitsunebi-proxy-utility/id1446584073">Kitsunebi for IOS</a><br>
            <a href="https://apps.apple.com/us/app/91vpn/id1483753706">91VPN for IOS</a>
        </p> 
            
    </div>
    <div class="box">
        <button class="accordion">Tutorial for Windows (Clash)</button>
        <div class="panel">
            <br>
            <br>
                <h2 class="subtitle">
                    Для приложения Clash
                </h2>
            <p>Перед настройкой в первую очередь вы должны быть<a href="{% url 'sspanel:register' %}">Зарегистрированы</a> и 
                <a href="{% url 'sspanel:login' %}">авторизованы</a>.
                <br/> </p>
            <p><strong>1. </strong> Устанавливаем приложение (Внимание! При установке может выйти уведомление от антивируса или от защитника Windows, нажимаем "Выполнить в любом случае" или нужно нажать подобное) (это не вирус!) </a></p>
            <p><strong>2. </strong> В личном кабинете нажимаем кнопку <strong>"Subscription address"</strong> копируем ссылку <strong>"Subscribe to Clash"</strong></p>
            <p><strong>3. </strong> Открываем Clash >> переходим в Profiles >> нужно вставить ранее скопированную ссылку и нажать <strong>"Download"</strong>.</p>
            <p><strong>4. </strong> Переходим в General >> включаем <strong>"System Proxy"</strong> (Если не работает можете перейти на >> "Proxies" выбрать нужный вам метод подключения)</p>
            <br>
            <br>
            <img src="{% static 'media/tutorial/win/1.png' %}" alt="download" width="500px"><br>
            <img src="{% static 'media/tutorial/win/2.png' %}" alt="download" width="500px"><br>
            <img src="{% static 'media/tutorial/win/3.png' %}" alt="download" width="500px"><br>
            <img src="{% static 'media/tutorial/win/4.png' %}" alt="download" width="500px"><br>
            <img src="{% static 'media/tutorial/win/5.png' %}" alt="download" width="500px"><br>
            <br>
            <br>
        </div>

        <button class="accordion">Tutorial for Android (Clash)</button>
        <div class="panel">
            <br>
            <br>
                <h2 class="subtitle">
                    Для приложения Clash
                </h2>
                <p>Перед настройкой в первую очередь вы должны быть<a href="{% url 'sspanel:register' %}">Зарегистрированы</a> и 
                    <a href="{% url 'sspanel:login' %}">авторизованы</a>. </p>
                <p><strong>1. </strong> Скачивание и установка приложения</p>
                <p><strong>2. </strong> В личном кабинете нажимаем кнопку <strong>"Subscription address"</strong> копируем ссылку <strong>"Subscribe to Clash"</strong></p>
                <p><strong>3. </strong> В приложении переходим в "Profiles" >> "New Profile" >> "URL" >> в "URL" вставляем ранее скопированную ссылку >> в "Auto Update" - пишем "30" >> "Name" - опционально. Сверху справа нажимаем на иконку >> "дискеты" >> три точки >> "Update" >> Выбираем нашу подписку. В главном экране нашего приложения нажимаем на кнопку "Stopped" (Подключаемся) </p>
            <br>
            <br>
            <img src="{% static 'media/tutorial/android/1.png' %}" alt="android" width="500px"><br>
            <img src="{% static 'media/tutorial/android/2.png' %}" alt="android" width="500px"><br>
            <br>
            <br>
        </div>

        <button class="accordion">Tutorial for IOS (Shadowrocket)</button>
        <div class="panel">
            <br>
            <br>
            <h2 class="subtitle">
                Для приложения Shadowrocket
            </h2>
            <p>Перед настройкой в первую очередь вы должны быть<a href="{% url 'sspanel:register' %}">Зарегистрированы</a> и 
                <a href="{% url 'sspanel:login' %}">авторизованы</a>. </p>
            <p><strong>1. </strong> Скачивание и установка приложения</p>
            <p><strong>2. </strong> В личном кабинете нажимаем кнопку <strong>"Subscription address"</strong> копируем ссылку <strong>"Subscribe to SS/Vmess"</strong></p>
            <p><strong>3. </strong> Дальше по картинкам.</p>
                <br>
                <br>
                <img src="{% static 'media/tutorial/ios/shadowrocket/1.png' %}" alt="android" width="500px"><br>
        </div>

        <button class="accordion">Tutorial for Mac OS (ClashX)</button>
        <div class="panel">
            <br>
            <br>
            <h2 class="subtitle">
                Для приложения ClashX.
            </h2>
            <p>Перед настройкой в первую очередь вы должны быть<a href="{% url 'sspanel:register' %}">Зарегистрированы</a> и 
                <a href="{% url 'sspanel:login' %}">авторизованы</a>.
                <br/> </p>
            <p><strong>1. </strong> Скачиваем и устанавливаем приложение </p>
            <p><strong>2. </strong> В личном кабинете нажимаем кнопку <strong>"Subscription address"</strong> копируем ссылку <strong>"Subscribe to Clash"</strong></p>
            <p><strong>3. Дальше по картинкам</strong></p>
            <br>
            <br>
            <img src="{% static 'media/tutorial/mac/1.png' %}" alt="android" width="500px"><br>
        </div>
    </div>
</div>

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;
    
    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight){
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }
    </script>

{% endblock main %}

templates/sspanel/index.html
{% extends 'base.html' %} {% load ehcofilter %}{% block main %}

<br /> {% if user.is_authenticated %}
<div class="box">
    <p class="title">Hello: {{ user.username }}</p>
    <button class="button">
        <a href="{% url 'sspanel:userinfo' %}">Go to billing</a>
    </button>

</div>
{% else %}
<div class="column box ">
    {% settings_value "ALLOW_REGISTER" as allow_register %}
    {% if allow_register is True %}
    <a class="button is-primary is-link" href="{% url 'sspanel:register' %}">Sign up</a>
    <a class="button is-danger is-outlined" href="{% url 'sspanel:login' %}">Login</a>
    {% else %}
    <h1 class="title"> Sorry</h1>
    <h2 class="subtitle">Registration is temporarily closed~</h2>
    {% endif %}
</div>
<br />

<br /> {% endif %} {% endblock main %}

templates/sspanel/login.html
{% extends 'base.html' %} {% load ehcofilter %}
{% block main %}

<div class="column is-12">
    {% if user.is_authenticated %}
    <div class="box">
        <p class="title">Hello: {{ user.username }}</p>
        <button class="button">
            <a href="{% url 'sspanel:userinfo' %}">Go to billing</a>
        </button>
    </div>
    {% else %}
    <div class="box">
        <h3 class="title">Login:</h3>
        <form class="form" action="{% url 'sspanel:login' %}" method="post">
            {% csrf_token %} {{ form.non_field_errors }} {% for field in form %} {{ field.label_tag }} {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %} {% endfor %}
            <hr>
            <div class="field is-grouped">
                <p class="control">
                    <button type="submit" class="button is-link">Login</button>
                </p>
                {% settings_value "USE_SMTP" as use_smtp %}
                {% if use_smtp %}
                <p class="control">
                    <a class="button is-white is-text" href="{% url 'password_reset' %}">Forgotten password</a>
                </p>
                {% endif %}
            </div>
        </form>
    </div>
</div>
{% endif %} {% endblock main %}

templates/sspanel/register.html
{% extends 'base.html' %} {% block main %}


<div class="column is-12">
    <div class="box">
        <h3 class="title">Sign up!</h3>
        <form class="form" action="{% url 'sspanel:register' %}" method="post">
            {% csrf_token %} {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %} {% endfor %}
            <hr>
            <div class="field is-grouped">
                <p class="control">
                    <button type="submit" class="button is-link">Sign up!</button>
                </p>
                <p class="control">
                    <a class="button is-white is-text" href="{% url 'sspanel:login' %}">Login</a>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock main%}

templates/sspanel/ticket.html
{% extends 'base.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-success">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    工单系统：
                </h1>
                <h2 class="subtitle">
                    有什么问题尽管提！什么时候解决就不知道了！
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">
        <div class="content">
            <p class="subtitle">我的工单:</p>
            <table class="table is-striped">
                <thead>
                    <tr>
                        <th>操作:</th>
                        <th>ID:</th>
                        <th>时间:</th>
                        <th>标题:</th>
                        <th>状态</th>
                    </tr>
                </thead>

                {% for record in ticket %}
                <tr>
                    <td><a class="button is-info" href="{% url 'sspanel:ticket_detail' record.pk %}">查看</a><br>
                        <a class="button is-danger" href="{% url 'sspanel:ticket_delete' record.pk %}">删除</a></td>
                    <td>#{{ record.pk }}</td>
                    <td>{{ record.time }}</td>
                    <td>{{ record.title }}</td>
                    <td>{{ record.get_status_display }}</td>
                </tr>
                {% empty %}
                <h2 class="subtitle">
                    暂时还没提过工单呢
                </h2>
                {% endfor %}
            </table>
            <p align="right"><a class="button is-danger is-outlined" href="{% url 'sspanel:ticket_create' %}">发起工单</a></p>
        </div>
    </div>
</div>
{% endblock main %}